name: Detect Changes

on:
  workflow_call:
    outputs:
      code:
        description: Whether application code changed
        value: ${{ jobs.changes.outputs.code }}

      deploy:
        description: Whether deployment-relevant files changed
        value: ${{ jobs.changes.outputs.deploy }}
      
      ecrEmpty:
        description: Whether the ECR repository is empty
        value: ${{ jobs.changes.outputs.ecrEmpty }}

permissions:
  contents: read
  id-token: write

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest

    outputs:
      code: ${{ steps.filter.outputs.code }}
      deploy: ${{ steps.filter.outputs.deploy }}
      ecrEmpty: ${{ steps.ecr.outputs.empty }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'src/**'
              - 'Dockerfile'

            deploy:
              - 'src/**'
              - 'Dockerfile'
              - 'ecs-parameters.yaml'
              - '.github/workflows/deploy.yaml'
      
      - name: Load image configuration
        run: |
          echo "ECR_REPOSITORY_FULL_NAME=$(yq -r '.image.nameSpace' ecs-parameters.yaml)/$(yq -r '.image.repository' ecs-parameters.yaml)" >> "$GITHUB_ENV"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ROLE_NAME }}
          aws-region: ${{ vars.AWS_REGION }}


      - name: Check ECR repository
        id: ecr
        run: |
          IMAGE_COUNT=$(aws ecr describe-images \
            --repository-name "$ECR_REPOSITORY_FULL_NAME" \
            --query 'length(imageDetails)' \
            --output text)

          if [ "$IMAGE_COUNT" -eq 0 ]; then
            echo "ECR repository is empty."
            echo "empty=true" >> "$GITHUB_OUTPUT"
          else
            echo "ECR repository contains $IMAGE_COUNT image(s)."
            echo "empty=false" >> "$GITHUB_OUTPUT"
          fi